#!/usr/bin/env bash

COMMITTER_NAME="Git Synchronizer"
COMMITTER_EMAIL="synchronizer@git-sync.org"

IGNORE_FILE=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/ignore
SYNC_FILE="./.git-sync"

DEBOUNCE_TIMEOUT=1

SYNCING=false

function git_sync {
    local now=$(date --iso-8601=seconds)

    git diff --exit-code HEAD > /dev/null; if [ $? -eq 0 ]; then
        # No differences since last commit.
        return
    fi

    GIT_COMMITTER_NAME=${COMMITTER_NAME} GIT_COMMITTER_EMAIL=${COMMITTER_EMAIL} \
            git commit --allow-empty -am "WIP - ${now}" > /dev/null; if [ $? -ne 0 ]; then
        # Commit did not succeed.
        return $?
    fi
    SYNCING=true

    local tree_hash=$(git log -1 --format="%T")
    if [ "$(cat ${SYNC_FILE} 2> /dev/null)" != ${tree_hash} ]; then
        echo "Syncing..."
        git push -f 2> /dev/null || return $?
        echo "Synced ${now}"
    fi

    git reset HEAD^ > /dev/null && echo ${tree_hash} > ${SYNC_FILE}
    SYNCING=false
}

function inotifywait_timeout() {
    local timeout=$1
    [ -z ${timeout} ] && timeout=-1

    inotifywait -rqq --exclude \.git --fromfile ${IGNORE_FILE} --event modify --timeout ${timeout} .
}

function inotifywait_debounce {
    local timeout=$1
    [ -z ${timeout} ] && timeout=-1

    inotifywait_timeout || exit $?
    while [ $? -eq 0 ]; do
        inotifywait_timeout ${timeout}
    done
    [ $? -ne 2 ] && exit $?
    return 0
}

function unsync {
    echo "Unsyncing..."
    if [ ${SYNCING} = true ]; then
        git reset HEAD^ > /dev/null
    fi
    git push -f 2> /dev/null && rm -f ${SYNC_FILE}
}

function main {
    trap unsync SIGHUP SIGINT SIGTERM
    git_sync || exit $?
    while :; do
        inotifywait_debounce ${DEBOUNCE_TIMEOUT} || exit $?
        git_sync || exit $?
    done
}


main
