#!/usr/bin/env bash

AUTHOR="Git Synchronizer <synchronizer@git-sync.org>"
SYNC_FILE="./.git-sync"

function git_sync {
    local now=$(date --iso-8601=seconds)

    git diff --exit-code > /dev/null; if [ $? -eq 0 ]; then
        # No differences since last commit.
        return
    fi

    git commit --allow-empty -am "WIP - ${now}" --author "${AUTHOR}" > /dev/null; if [ $? -ne 0 ]; then
        # Commit did not succeed.
        return $?
    fi

    local tree_hash=$(git log -1 --format="%T")
    if [ "$(cat ${SYNC_FILE} 2> /dev/null)" != ${tree_hash} ]; then
        echo "Syncing..."
        git push -f 2> /dev/null && echo ${tree_hash} > ${SYNC_FILE} || exit $?
        echo "Synced ${now}"
    fi

    git reset HEAD^ > /dev/null
}

function unsync {
    echo "Unsyncing..."
    git push -f 2> /dev/null && rm -f ${SYNC_FILE}
}

function main {
    trap unsync SIGHUP SIGINT SIGTERM
    git_sync || exit $?
    while :; do
        inotifywait -rqq --exclude \.git --exclude \.git-sync --event modify . || exit $?
        git_sync || exit $?
    done
}


main
